### ISSUE TITLE
在ubuntu 下使用问题

### ISSUE THREAD

**Issue by jiuxiaxixi** [iyannik0215/CrawlerIShadowsocks#4]

**Comment by jiuxiaxixi** [comment]
目前使用的sslocal 来代理 请问
`go run main.go -h
main.go:6:2: cannot find package "github.com/codegangsta/cli" in any of:
    /usr/lib/go-1.6/src/github.com/codegangsta/cli (from $GOROOT)
    ($GOPATH not set)
main.go:7:2: cannot find package "github.com/iyannik0215/CrawlerIShadowsocks/cmd" in any of:
    /usr/lib/go-1.6/src/github.com/iyannik0215/CrawlerIShadowsocks/cmd (from $GOROOT)
    ($GOPATH not set)
main.go:8:2: cannot find package "github.com/iyannik0215/CrawlerIShadowsocks/conf" in any of:
    /usr/lib/go-1.6/src/github.com/iyannik0215/CrawlerIShadowsocks/conf (from $GOROOT)
    ($GOPATH not set)
`
出现了如下的问题

**Comment by jiuxiaxixi** [comment]
请问如何解决

**Comment by jiuxiaxixi** [comment]
非常感谢作者

**Comment by yakumioto** [comment]
github.com/codegangsta/cli 的包已经被迁移了. 而且包也被更新的 V2 版本了.  如果你会写Go的话可以改改.. github.com/urfave/cli

**Comment by jiuxiaxixi** [comment]
感谢  

Sent from [Nylas N1](https://link.nylas.com/link/bsz2sbab2d9iicsi92jafe8rz
/local-1945cd4d-501d/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1&r=cmVw
bHkrMDBjOWEyNWNlOTgyZWZhMmZhNWQxMzc4ZDc1YzY0ZWViOTQ0NzNkNDY4MTUxYjFmOTJjZjAwMD
AwMDAxMTNjNTE3MTM5MmExNjljZTBhMmUxYWY2QHJlcGx5LmdpdGh1Yi5jb20=), the
extensible, open source mail
client.![](https://link.nylas.com/open/bsz2sbab2d9iicsi92jafe8rz/local-
1945cd4d-501d?r=cmVwbHkrMDBjOWEyNWNlOTgyZWZhMmZhNWQxMzc4ZDc1YzY0ZWViOTQ0NzNkND
Y4MTUxYjFmOTJjZjAwMDAwMDAxMTNjNTE3MTM5MmExNjljZTBhMmUxYWY2QHJlcGx5LmdpdGh1Yi5j
b20=)
